use std::{env, fmt::Write as _, fs, path::PathBuf};

fn main() {
    embuild::espidf::sysenv::output();
    convert_assets();
}

/// Every 1bpp asset the firmware draws.
///
/// Listed explicitly rather than globbed: a missing file should break the build
/// with the name of what is missing, and a stray file in the directory should
/// not silently become part of the binary.
const ASSETS: &[(&str, &str)] = &[("LOGO", "logo")];

/// Strip each PBM's header, drop the raw payload in `OUT_DIR`, and generate a
/// `Bitmap` constant for each one.
///
/// ## Why a build script rather than committed binaries
///
/// The `.pbm` files stay the source of truth because they are *viewable* — any
/// image tool opens them and a reviewer can see what changed. Committed blobs
/// would be opaque in git and would drift from whatever produced them.
/// Re-exporting artwork then needs no code change at all.
///
/// ## Why PBM
///
/// A binary (P4) PBM **is already** what the panel wants: 1 bit per pixel,
/// packed MSB-first, rows padded to byte boundaries. The only work is removing
/// a short ASCII header. A PNG would need a decoder in the firmware, or a
/// heavier build step, to arrive at the same bytes.
fn convert_assets() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let mut generated = String::from(
        "// Generated by build.rs from assets/*.pbm -- do not edit.\n\
         // Each payload is 1bpp, MSB-first, rows padded to byte boundaries.\n\n",
    );

    for (konst, stem) in ASSETS {
        let src = PathBuf::from(format!("assets/{stem}.pbm"));
        println!("cargo:rerun-if-changed={}", src.display());

        let raw = fs::read(&src).unwrap_or_else(|e| panic!("cannot read {}: {e}", src.display()));
        let (width, height, data) = parse_p4(&raw, &src.display().to_string());

        // The draw path indexes with a stride computed from `width`, so a
        // truncated payload would render as diagonal mush rather than fail.
        // Catch it here, where the message can name the file.
        let expected = (width + 7) / 8 * height;
        assert_eq!(
            data.len(),
            expected,
            "{}: payload is {} bytes, expected {expected} for {width}x{height}",
            src.display(),
            data.len(),
        );

        let bin = out_dir.join(format!("{stem}.bin"));
        fs::write(&bin, data).unwrap_or_else(|e| panic!("cannot write {}: {e}", bin.display()));

        writeln!(
            generated,
            "pub static {konst}: Bitmap = Bitmap {{\n    \
                 width: {width},\n    \
                 height: {height},\n    \
                 bits: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{stem}.bin\")),\n\
             }};\n",
        )
        .unwrap();
    }

    fs::write(out_dir.join("assets.rs"), generated).unwrap();
}

/// Minimal P4 (binary PBM) header parser.
///
/// The format is `P4`, whitespace-separated width and height, then **exactly
/// one** whitespace byte, then packed pixel data. Comments (`#` to end of line)
/// may appear anywhere in the header — GIMP writes one on every export, and
/// that is the part naive parsers get wrong.
fn parse_p4<'a>(raw: &'a [u8], name: &str) -> (usize, usize, &'a [u8]) {
    // `&raw[..2]` on a shorter file panics with "range end index 2 out of
    // range" before this assert can say anything useful, so test the prefix in
    // a way that tolerates a short slice.
    assert!(
        raw.starts_with(b"P4"),
        "{name}: not a binary (P4) PBM -- re-export as Raw, not ASCII",
    );

    let mut i = 2;
    let mut fields = Vec::new();

    while fields.len() < 2 {
        while i < raw.len() && raw[i].is_ascii_whitespace() {
            i += 1;
        }
        if raw.get(i) == Some(&b'#') {
            while i < raw.len() && raw[i] != b'\n' {
                i += 1;
            }
            continue;
        }
        let start = i;
        while i < raw.len() && !raw[i].is_ascii_whitespace() {
            i += 1;
        }
        let text = std::str::from_utf8(&raw[start..i]).expect("bad PBM header");
        fields.push(text.parse::<usize>().expect("bad PBM dimension"));
    }

    // Exactly one whitespace byte separates header from data -- by
    // specification, not "skip all whitespace". Getting this wrong eats the
    // first row of any image whose leading pixel byte happens to look like
    // whitespace.
    //
    // **`\r\n` counts as that one separator.** A header written with DOS line
    // endings otherwise leaves the `\n` as the first pixel byte, which shifts
    // the whole bitmap by one and fails the length check below with a message
    // about sizes that says nothing about the real cause.
    if raw.get(i) == Some(&b'\r') && raw.get(i + 1) == Some(&b'\n') {
        i += 2;
    } else {
        i += 1;
    }

    (fields[0], fields[1], &raw[i..])
}
