//! Screen layout (§6).
//!
//! Draws into a plain framebuffer and never touches SPI — `display` owns the
//! hardware. That split is what lets a layout be reasoned about, and eventually
//! tested, without a panel anywhere near it.
//!
//! ## What the panel size changes
//!
//! 800×480 is nineteen times the area of the moisture project's 200×200, and
//! the temptation is to fill it. The constraint that stops that is unchanged:
//! **every refresh is full**, and a full refresh on a UC8179 takes seconds. So
//! the layout is built to be read at a glance from across a room, not to be
//! dense — the extra area buys *size*, not *more*.

use core::fmt::Write as _;

use embedded_graphics::mono_font::ascii::{FONT_10X20, FONT_6X10, FONT_8X13, FONT_9X15};
use embedded_graphics::mono_font::MonoTextStyle;
use embedded_graphics::prelude::*;
use embedded_graphics::primitives::{Line, PrimitiveStyle, Rectangle};
use embedded_graphics::text::{Alignment, Baseline, Text, TextStyleBuilder};
use epd_waveshare::epd7in5_v2::Display7in5;
use u8g2_fonts::types::{FontColor, VerticalPosition};
use u8g2_fonts::{fonts, FontRenderer};

use crate::as3935::{Distance, Location};
use crate::display::{HEIGHT, INK, PAPER, WIDTH};
use crate::system::Health;

/// A 1bpp image: width, height, and MSB-first packed rows.
pub struct Bitmap {
    pub width: usize,
    pub height: usize,
    pub bits: &'static [u8],
}

impl Bitmap {
    /// Bytes per row. Rows are byte-aligned, so a 480 px image is exactly 60
    /// bytes wide with no padding.
    const fn stride(&self) -> usize {
        (self.width + 7) / 8
    }

    fn pixel(&self, x: usize, y: usize) -> bool {
        (self.bits[y * self.stride() + (x >> 3)] >> (7 - (x & 7))) & 1 == 1
    }
}

// Generated by build.rs from assets/*.pbm: LOGO.
include!(concat!(env!("OUT_DIR"), "/assets.rs"));

/// Draw a bitmap with its top-left corner at `at`.
///
/// **A set bit in a PBM means black**, which on this panel means [`INK`] — so
/// the inversion documented in `display` applies here too, and for the same
/// reason it is applied once rather than at every call site.
fn blit(frame: &mut Display7in5, image: &Bitmap, at: Point) {
    for y in 0..image.height {
        for x in 0..image.width {
            if image.pixel(x, y) {
                let _ = Pixel(Point::new(at.x + x as i32, at.y + y as i32), INK).draw(frame);
            }
        }
    }
}

/// Who built it.
///
/// Written the way it was given, with `AT` rather than `@`. That is the
/// author's own convention and it is kept literally — a one-word change here if
/// the symbol is wanted instead.
const AUTHOR: &str = "Leonid.Moiseichuk AT gmail.com";

/// The cold-boot splash.
///
/// Worth the four seconds it costs. A device that takes nearly a minute to say
/// anything useful — the sensor has to settle, and the first status screen is
/// gated behind a batch window — otherwise gives no sign it started at all, and
/// "did it boot?" is the first question anyone asks of a box with one button.
pub fn logo(frame: &mut Display7in5) {
    let _ = frame.clear(PAPER);

    // Centred on both axes. The artwork is 480x480 on an 800x480 panel, so it
    // is full-height and the centring only does anything horizontally -- but
    // computing it means a re-exported logo of another size still lands right.
    let at = Point::new(
        (WIDTH as i32 - LOGO.width as i32) / 2,
        (HEIGHT as i32 - LOGO.height as i32) / 2,
    );
    blit(frame, &LOGO, at);

    let mut version = Text32::new();
    let _ = version.push_str("fw ");
    let _ = version.push_str(env!("CARGO_PKG_VERSION"));
    let _ = Text::with_alignment(
        &version,
        Point::new(WIDTH as i32 - 16, HEIGHT as i32 - 22),
        MonoTextStyle::new(&FONT_9X15, INK),
        Alignment::Right,
    )
    .draw(frame);

    // Bottom left, balancing the version on the right. The artwork is 480 px
    // wide and centred on an 800 px panel, so it occupies x=160..640 — both
    // bottom corners are clear of it whatever the logo contains.
    let _ = Text::with_baseline(
        AUTHOR,
        Point::new(16, HEIGHT as i32 - 26),
        MonoTextStyle::new(&FONT_9X15, INK),
        Baseline::Top,
    )
    .draw(frame);
}

/// The number meant to be read from across the room.
const HEADLINE: FontRenderer = FontRenderer::new::<fonts::u8g2_font_fub42_tr>();
/// Section headings and gauge labels.
const LABEL: FontRenderer = FontRenderer::new::<fonts::u8g2_font_fub14_tr>();
/// Row-2 labels — regular weight, because a label is not the information.
const FIELD_LABEL: FontRenderer = FontRenderer::new::<fonts::u8g2_font_helvR14_tr>();
/// Row-2 values — bold, same size, so the eye lands on the number rather than
/// on the word introducing it.
const FIELD_VALUE: FontRenderer = FontRenderer::new::<fonts::u8g2_font_helvB14_tr>();

type Text16 = heapless::String<16>;
type Text32 = heapless::String<32>;
type Text64 = heapless::String<64>;

/// Top of the status line's text.
///
/// Not zero: the panel's first rows are the ones most likely to be lost to a
/// bezel or a marginal edge, and a status line that has to be read at an angle
/// should not start at the very first pixel.
const STATUS_TOP: i32 = 6;

/// Everything the status screen shows.
pub struct Status<'a> {
    pub location: Location,
    /// Measured antenna resonance, kHz — from the LCO self-test.
    pub antenna_khz: u32,
    pub irq_confirmed: bool,
    /// §4.2's defence level and its ceiling.
    pub defence_level: u8,
    pub defence_max: u8,
    pub strikes_total: u32,
    /// The most recent strike: distance, intensity, and when — if there has
    /// been one, and if the clock was set at the time.
    pub last_strike: Option<(Distance, u32, Option<u64>)>,
    /// Disturbers counted since boot — the honest measure of how hostile the
    /// location is, and the number that decides whether a quiet screen means
    /// "no storms" or "this spot is unusable".
    pub disturbers_total: u32,
    /// Device health, drawn as the status line.
    pub health: Health,
    /// `None` when the gauge is absent or did not answer.
    pub battery: Option<crate::battery::Reading>,
    /// Wall-clock time, or `None` if the clock has never been set (§5).
    ///
    /// `None` is not an error and is shown as such: a device that has not been
    /// told the time is still detecting strikes, it just cannot stamp them —
    /// and every record it writes meanwhile carries an empty timestamp, which
    /// is worth knowing from across the room.
    pub now: Option<u64>,
    /// Minutes since boot. Shown only when there is no wall clock, as the
    /// nearest honest substitute.
    pub uptime_minutes: u32,
    /// Everything seen in the last hour (§4.3).
    pub last_hour: crate::history::Bucket,
    /// The learned cell range, low/high mV (§2.1).
    pub battery_range: (u16, u16),
    /// Which period the charts show.
    pub chart_period: ChartPeriod,
    /// Strikes per bucket, oldest first — the count chart.
    pub chart_counts: &'a [u16],
    /// Mean score per bucket in thousandths, oldest first, `0` for an empty
    /// bucket. The severity chart.
    pub chart_scores: &'a [u32],
    /// How many buckets the ring holds when full.
    ///
    /// Separate from the slice length so the column width stays fixed as the
    /// ring fills: bars that grow narrower over the first day would make two
    /// readings of the same chart incomparable.
    pub chart_capacity: usize,
    /// Whether `esp_pm` is actually light-sleeping, read back rather than
    /// assumed (§7).
    pub light_sleep: bool,
}

/// Draw the status screen.
pub fn status(frame: &mut Display7in5, s: &Status<'_>) {
    let _ = frame.clear(PAPER);
    let black = PrimitiveStyle::with_stroke(INK, 1);

    // --- status line ------------------------------------------------------
    //
    // The device talking about itself: clock, die temperature, memory, battery.
    // One line, at the top, small. In a box that runs unattended for weeks this
    // is the only way to ask whether the machine under the readings is healthy —
    // and none of it is about the weather, which is why it is kept out of the
    // way of everything that is.
    status_line(frame, s);

    let _ = Line::new(Point::new(16, 30), Point::new(WIDTH as i32 - 16, 30))
        .into_styled(black)
        .draw(frame);

    // --- mode and noise defence -------------------------------------------
    //
    // This row used to read "LIGHTNING TERMINAL", which is the one fact anyone
    // looking at the device already knows. It now carries the two settings that
    // change how the sensor behaves and that nothing else on screen reveals:
    // which AFE gain is selected, and how hard the receiver is currently
    // fighting noise.
    field(frame, Point::new(16, 62), "Mode: ", s.location.label());
    // What changes it, said on the glass. There is exactly one button and no
    // other label anywhere on the device, so a sealed box otherwise gives no
    // clue that pressing it does anything at all.
    let _ = Text::with_baseline(
        "hold BOOT to switch",
        Point::new(16, 70),
        MonoTextStyle::new(&FONT_6X10, INK),
        Baseline::Top,
    )
    .draw(frame);

    // The gauge sits on this row rather than in the middle of the screen: it is
    // a setting, not a measurement, and it belongs beside the other one.
    gauge(
        frame,
        Point::new(180, 62),
        s.defence_level as u32,
        s.defence_max as u32,
    );

    // Disturbers for this session. It belongs beside the noise gauge because it
    // is what the gauge is *responding to* -- a high level with few disturbers
    // means a quiet spot the ladder has not relaxed from yet, and a low level
    // with thousands means the auto-tune is losing.
    let mut count = Text16::new();
    let _ = write!(count, "{}", s.disturbers_total);
    field(frame, Point::new(600, 62), "Disturbers: ", &count);

    let _ = Line::new(Point::new(16, 84), Point::new(WIDTH as i32 - 16, 84))
        .into_styled(black)
        .draw(frame);

    // --- the headline: total strikes --------------------------------------
    //
    // The one number the device exists to report. Everything else on this
    // screen is context for it.
    let mut count = Text16::new();
    let _ = write!(count, "{}", s.strikes_total);
    let _ = HEADLINE.render(
        count.as_str(),
        Point::new(16, 158),
        VerticalPosition::Baseline,
        FontColor::Transparent(INK),
        frame,
    );
    let _ = LABEL.render(
        if s.strikes_total == 1 { "strike" } else { "strikes" },
        Point::new(16, 190),
        VerticalPosition::Baseline,
        FontColor::Transparent(INK),
        frame,
    );

    // --- the last hour ----------------------------------------------------
    //
    // §4.3's three figures. Count says how *busy*, mean score says how *severe*,
    // and distance says how *close* -- and none of the three substitutes for
    // another. One violent overhead strike and a hundred distant ones produce
    // the same count and wildly different scores; the reverse is true of the
    // mean.
    stats(frame, s);

    // --- last strike ------------------------------------------------------
    let mut last = Text64::new();
    match s.last_strike {
        Some((distance, intensity_milli, when)) => {
            let _ = last.push_str(match distance {
                Distance::Overhead => "overhead",
                Distance::OutOfRange => "out of range",
                Distance::Km(_) => "",
            });
            if let Distance::Km(km) = distance {
                let _ = write!(last, "{}", km as u32);
                let _ = last.push_str(" km");
            }
            let _ = last.push_str("  ·  intensity ");
            let _ = write!(last, "{}", intensity_milli / 1000);
            // When, to the minute. The point of the strike readout is "what is
            // happening", and a distance with no time cannot say whether it is
            // happening now or happened yesterday.
            if let Some(epoch) = when {
                let stamp = crate::clock::format_local(epoch);
                let _ = last.push_str("  ·  ");
                let _ = last.push_str(stamp.get(11..16).unwrap_or(""));
            }
        }
        None => {
            let _ = last.push_str("no strikes yet");
        }
    }
    let _ = Text::with_baseline(
        &last,
        Point::new(320, 138),
        MonoTextStyle::new(&FONT_10X20, INK),
        Baseline::Top,
    )
    .draw(frame);

    // --- the charts -------------------------------------------------------
    charts(frame, s);

    // --- the bring-up facts, small, at the foot ---------------------------
    //
    // Small because they matter once — but they matter a lot then, and a sealed
    // device with no console has nowhere else to say them.
    let mut antenna = Text32::new();
    let _ = antenna.push_str("antenna ");
    let _ = write!(antenna, "{}", s.antenna_khz);
    let _ = antenna.push_str(" kHz · IRQ ");
    let _ = antenna.push_str(if s.irq_confirmed { "OK" } else { "NOT CONFIRMED" });
    let _ = antenna.push_str(" · disturbers ");
    let _ = write!(antenna, "{}", s.disturbers_total);
    // The learned cell range, small and at the foot. It is a slow-moving
    // diagnostic rather than a reading — but it is the number that says whether
    // the runtime prediction above it has anything behind it, and a pack whose
    // observed maximum has fallen is a cell that is ageing.
    let _ = antenna.push_str(" · cell ");
    let _ = write!(antenna, "{}", s.battery_range.0 as u32);
    let _ = antenna.push('-');
    let _ = write!(antenna, "{}", s.battery_range.1 as u32);
    let _ = antenna.push_str(" mV");

    let _ = Line::new(
        Point::new(16, HEIGHT as i32 - 40),
        Point::new(WIDTH as i32 - 16, HEIGHT as i32 - 40),
    )
    .into_styled(black)
    .draw(frame);
    let _ = Text::with_baseline(
        &antenna,
        Point::new(16, HEIGHT as i32 - 32),
        MonoTextStyle::new(&FONT_6X10, INK),
        Baseline::Top,
    )
    .draw(frame);
}

/// A labelled horizontal bar.
///
/// Deliberately a bar rather than a number: the question these answer is "how
/// close to the limit", which a filled proportion says at a glance and a
/// figure makes you compute.
fn gauge(frame: &mut Display7in5, at: Point, value: u32, max: u32) {
    const BAR_WIDTH: u32 = 200;
    const BAR_HEIGHT: u32 = 22;

    // **Measured, not assumed.** A hardcoded label width put the bar through
    // the "e" of "Noise" -- proportional text is not 8 px a character, and the
    // number that would have to be right is exactly the one nobody can predict
    // from reading the code. Asking the renderer how wide it drew cannot drift.
    const GAP: i32 = 10;
    let label_width = FIELD_LABEL
        .render(
            "Noise",
            Point::new(at.x, at.y),
            VerticalPosition::Baseline,
            FontColor::Transparent(INK),
            frame,
        )
        .map(|dims| dims.advance.x)
        .unwrap_or(48);

    let bar_x = at.x + label_width + GAP;
    let bar = Rectangle::new(
        Point::new(bar_x, at.y - 16),
        Size::new(BAR_WIDTH, BAR_HEIGHT),
    );
    let _ = bar
        .into_styled(PrimitiveStyle::with_stroke(INK, 2))
        .draw(frame);

    if max > 0 && value > 0 {
        // Inset by the stroke so the fill does not sit on the border.
        let filled = (BAR_WIDTH - 4) * value.min(max) / max;
        let _ = Rectangle::new(
            Point::new(bar_x + 2, at.y - 14),
            Size::new(filled, BAR_HEIGHT - 4),
        )
        .into_styled(PrimitiveStyle::with_fill(INK))
        .draw(frame);
    }

    // The number alone. The rung name -- "noise floor", "watchdog", "spike
    // rejection" -- is which register the ladder happens to be working on, and
    // that is a fact about the implementation rather than about the weather. It
    // stays on the console, where it is a debugging aid.
    let mut caption = Text32::new();
    let _ = write!(caption, "{}", value);
    let _ = caption.push('/');
    let _ = write!(caption, "{}", max);
    let _ = Text::with_baseline(
        &caption,
        Point::new(bar_x + BAR_WIDTH as i32 + GAP, at.y - 14),
        MonoTextStyle::new(&FONT_9X15, INK),
        Baseline::Top,
    )
    .draw(frame);
}

/// Append a decimal `u32` without `format!`.
///
/// The render path runs on a device that is meant to stay up for weeks;
/// `format!` allocates, and the allocation is avoidable here for the sake of
/// four lines.


/// The device's own vital signs, as one line.
fn status_line(frame: &mut Display7in5, s: &Status<'_>) {
    // **8x13, not 9x15, and the arithmetic is the reason.** The two halves are
    // drawn independently -- left from x=16, right anchored to x=WIDTH-16 --
    // so nothing stops them meeting in the middle. At the widest realistic
    // values the line is about 86 characters:
    //
    //     2026-08-02 23:27  160MHz  38.1C  ram 264/52KB  flash 1976/0KB
    //     batt 97% 4.16V  12h left
    //
    // which at 9 px each needs 806 px on an 800 px panel. The right half was
    // overwriting the left, and "batt" was where it landed. At 8 px the same
    // line is 720 px, leaving ~80 px of slack for values that grow -- a filling
    // log turns "1976/0KB" into "1000/976KB", which is four characters more.
    let style = MonoTextStyle::new(&FONT_8X13, INK);
    let mut left = Text64::new();

    // The clock, when there is one. Date and time to the minute -- seconds
    // would be false precision on a panel that refreshes every five minutes.
    //
    // Uptime is the fallback rather than the default, now that §5's clock
    // exists. It is shown with a marker rather than silently, because the same
    // gap that leaves this line without a time leaves every strike record
    // without one.
    match s.now {
        Some(epoch) => {
            let stamp = crate::clock::format_local(epoch);
            // "YYYY-MM-DD HH:MM:SS" -- take everything but the seconds.
            let _ = left.push_str(stamp.get(..16).unwrap_or(stamp.as_str()));
        }
        None => {
            let _ = left.push_str("no clock, up ");
            let hours = s.uptime_minutes / 60;
            if hours > 0 {
                let _ = write!(left, "{}", hours);
                let _ = left.push('h');
            }
            let _ = write!(left, "{}", s.uptime_minutes % 60);
            let _ = left.push('m');
        }
    }

    // The live clock, and whether light sleep is running. Both come from what
    // the chip reports rather than from what the policy asked for — and this is
    // the only witness there is once USB is cut, because cutting USB also cuts
    // the console. Unplug, press BOOT, read the line.
    let _ = left.push_str("  ");
    let _ = write!(left, "{}", s.health.cpu_mhz);
    let _ = left.push_str("MHz");
    if s.light_sleep {
        let _ = left.push_str(" +sleep");
    }

    if let Some(tenths) = s.health.die_temp_tenths {
        let _ = left.push_str("  ");
        if tenths < 0 {
            let _ = left.push('-');
        }
        let magnitude = tenths.unsigned_abs();
        let _ = write!(left, "{}", magnitude / 10);
        let _ = left.push('.');
        let _ = write!(left, "{}", magnitude % 10);
        let _ = left.push('C');
    }

    // free/used, both of them, in the same unit. A bare percentage was
    // ambiguous in the one way that matters -- "99%" reads equally as
    // nearly-full and nearly-empty, and those are opposite emergencies.
    // "ram" rather than "heap": heap is an implementation word, and the line is
    // read by whoever is standing in front of the device, not by whoever wrote
    // the allocator.
    let _ = left.push_str("  ram ");
    let _ = write!(left, "{}", s.health.heap_kb.0);
    let _ = left.push('/');
    let _ = write!(left, "{}", s.health.heap_kb.1);
    let _ = left.push_str("KB");

    if let Some((free, used)) = s.health.flash_kb {
        let _ = left.push_str("  flash ");
        let _ = write!(left, "{}", free);
        let _ = left.push('/');
        let _ = write!(left, "{}", used);
        let _ = left.push_str("KB");
    }

    // The two halves are drawn independently and could in principle collide, so
    // the left one is kept short deliberately -- abbreviations here are not
    // terseness for its own sake, they are what keeps the battery readout from
    // running into the flash figures at the widest values.
    let _ = Text::with_baseline(&left, Point::new(16, STATUS_TOP), style, Baseline::Top).draw(frame);

    // Battery on the right, because it is the one field a passer-by looks for.
    let mut right = Text64::new();
    match s.battery {
        Some(reading) => {
            let _ = right.push_str("batt ");
            let _ = write!(right, "{}", reading.percent as u32);
            let _ = right.push_str("%  ");
            let _ = write!(right, "{}", reading.millivolts as u32 / 1000);
            let _ = right.push('.');
            let hundredths = (reading.millivolts % 1000) / 10;
            if hundredths < 10 {
                let _ = right.push('0');
            }
            let _ = write!(right, "{}", hundredths as u32);
            let _ = right.push_str(" V");

            // **Every state says something.** The first version had two
            // branches -- charging, or an estimate -- and a cell sitting at
            // exactly 0.00 %/hr matched neither, so a full battery on USB
            // showed a percentage and a voltage with nothing after it. That
            // reads as a missing feature rather than as a resting cell.
            if reading.is_charging() {
                let _ = right.push_str("  charging");
            } else if reading.crate_centi_per_hour == 0 {
                // Neither direction. Distinguish a topped-up cell from one
                // simply not being asked for anything, because they mean
                // different things about what happens next.
                let _ = right.push_str(if reading.percent >= 97 {
                    "  full"
                } else {
                    "  idle"
                });
            } else {
                // **Two predictions, and the learned one wins where it exists.**
                //
                // The gauge divides its own percentage by its own rate — self-
                // consistent, and wrong in the same direction as the gauge
                // whenever the gauge is wrong about this cell. The learned
                // figure asks how much of the range *this unit has actually
                // observed* is left, and how fast it is being crossed.
                //
                // They part company near empty, where a LiPo falls off a cliff
                // and a percentage flatters the time remaining. The learned one
                // is preferred once the observed span is wide enough to divide
                // by; until then there is nothing to prefer and the gauge's
                // model is the better guess.
                let hours = crate::battery::hours_from_range(s.battery_range, &reading)
                    .or_else(|| reading.hours_remaining());
                match hours {
                    Some(hours) if hours >= 48 => {
                        let _ = right.push_str("  ");
                        let _ = write!(right, "{}", hours / 24);
                        let _ = right.push_str("d left");
                    }
                    Some(hours) => {
                        let _ = right.push_str("  ");
                        let _ = write!(right, "{}", hours);
                        let _ = right.push_str("h left");
                    }
                    // Discharging, but too slowly to divide by. Say the
                    // direction rather than nothing: §2.1's CRATE averages over
                    // minutes, so a device just unplugged genuinely has no
                    // estimate yet — and a number there would be a division by
                    // nearly zero wearing a hat.
                    None => {
                        let _ = right.push_str("  discharging");
                    }
                }
            }
        }
        None => {
            let _ = right.push_str("batt -- no gauge");
        }
    }

    // **Right-aligned AND top-baselined.** `Text::with_alignment` alone leaves
    // the vertical baseline at its default -- alphabetic -- which draws the text
    // *above* the given y. At the top of the panel that clips the first few
    // pixel rows off the glass, while the left-hand half of the same line sits
    // correctly because it was built with `with_baseline`. Two calls, two
    // different defaults, one line that looked half-broken.
    let right_style = TextStyleBuilder::new()
        .alignment(Alignment::Right)
        .baseline(Baseline::Top)
        .build();
    let _ = Text::with_text_style(
        &right,
        Point::new(WIDTH as i32 - 16, STATUS_TOP),
        style,
        right_style,
    )
    .draw(frame);
}


/// The last hour's three figures, in a row under the headline.
fn stats(frame: &mut Display7in5, s: &Status<'_>) {
    const TOP: i32 = 232;
    const COLUMN: i32 = 190;

    let hour = &s.last_hour;

    let mut count = Text16::new();
    let _ = write!(count, "{}", hour.strikes as u32);
    stat(frame, Point::new(16, TOP), "strikes / hour", &count);

    let mut score = Text16::new();
    match hour.mean_score_milli() {
        Some(milli) => {
            let _ = write!(score, "{}", milli / 1000);
            let _ = score.push('.');
            let hundredths = (milli % 1000) / 10;
            if hundredths < 10 {
                let _ = score.push('0');
            }
            let _ = write!(score, "{}", hundredths);
        }
        // A dash, not a zero. Zero is a score, and an hour with no strikes did
        // not score zero -- it has no score at all, and the two mean opposite
        // things about the weather.
        None => {
            let _ = score.push('-');
        }
    }
    stat(frame, Point::new(16 + COLUMN, TOP), "mean score", &score);

    let mut distance = Text16::new();
    match hour.mean_distance_km() {
        Some(km) => {
            let _ = write!(distance, "{}", km);
            let _ = distance.push_str(" km");
        }
        None => {
            let _ = distance.push('-');
        }
    }
    stat(frame, Point::new(16 + COLUMN * 2, TOP), "mean distance", &distance);

    let mut closest = Text16::new();
    if hour.distance_km_min == u8::MAX {
        let _ = closest.push('-');
    } else {
        let _ = write!(closest, "{}", hour.distance_km_min as u32);
        let _ = closest.push_str(" km");
    }
    stat(frame, Point::new(16 + COLUMN * 3, TOP), "closest", &closest);
}

/// One labelled figure: value large, label small beneath it.
fn stat(frame: &mut Display7in5, at: Point, label: &str, value: &str) {
    let _ = LABEL.render(
        value,
        Point::new(at.x, at.y),
        VerticalPosition::Baseline,
        FontColor::Transparent(INK),
        frame,
    );
    let _ = Text::with_baseline(
        label,
        Point::new(at.x, at.y + 8),
        MonoTextStyle::new(&FONT_9X15, INK),
        Baseline::Top,
    )
    .draw(frame);
}


/// A regular-weight label followed by a bold value.
///
/// The split is the point: a label is not the information, it is the word that
/// says what the information is. Setting both in bold — which is what the old
/// row did — makes the eye work to find the part that changes.
///
/// Returns the x the value ended at, so callers can pack a line by hand.
fn field(frame: &mut Display7in5, at: Point, label: &str, value: &str) -> i32 {
    let advance = FIELD_LABEL
        .render(
            label,
            at,
            VerticalPosition::Baseline,
            FontColor::Transparent(INK),
            frame,
        )
        .map(|dims| dims.advance.x)
        .unwrap_or(0);

    let after = FIELD_VALUE
        .render(
            value,
            Point::new(at.x + advance, at.y),
            VerticalPosition::Baseline,
            FontColor::Transparent(INK),
            frame,
        )
        .map(|dims| dims.advance.x)
        .unwrap_or(0);

    at.x + advance + after
}


/// Which span the charts cover.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ChartPeriod {
    Day,
    Week,
    Month,
}

impl ChartPeriod {
    pub fn label(self) -> &'static str {
        match self {
            ChartPeriod::Day => "24 hours",
            ChartPeriod::Week => "7 days",
            ChartPeriod::Month => "30 days",
        }
    }
}

/// Two stacked charts across the foot of the screen: how many, and how severe.
///
/// **Both, because neither answers the other's question.** A count says how
/// busy the sky was; a mean score says how dangerous. One violent overhead
/// strike and a hundred distant ones give the same count and wildly different
/// scores, and the reverse is true of the mean — so §4.3 keeps both and this
/// draws both, one above the other on a shared time axis.
fn charts(frame: &mut Display7in5, s: &Status<'_>) {
    const TOP: i32 = 290;
    const HEIGHT: u32 = 60;
    const GAP: i32 = 26;
    let left = 16;
    let width = WIDTH as i32 - 32;

    let mut title = Text32::new();
    let _ = title.push_str("Last ");
    let _ = title.push_str(s.chart_period.label());
    let _ = FIELD_LABEL.render(
        title.as_str(),
        Point::new(left, TOP - 6),
        VerticalPosition::Baseline,
        FontColor::Transparent(INK),
        frame,
    );

    chart(
        frame,
        Point::new(left, TOP),
        width,
        HEIGHT,
        "strikes",
        s.chart_counts.iter().map(|v| *v as u32),
        s.chart_capacity,
    );
    chart(
        frame,
        Point::new(left, TOP + HEIGHT as i32 + GAP),
        width,
        HEIGHT,
        "mean score",
        s.chart_scores.iter().copied(),
        s.chart_capacity,
    );
}

/// One auto-scaled bar chart.
///
/// **Auto-scaled, as §4.3 requires**, because score rises sharply as a storm
/// closes — a fixed ceiling would either clip an overhead strike or flatten
/// everything else into the baseline. The peak is printed beside the label, so
/// the scale is never a mystery: two charts drawn on different days are not
/// comparable by height alone, and the number is what makes them comparable.
fn chart<I>(
    frame: &mut Display7in5,
    at: Point,
    width: i32,
    height: u32,
    label: &str,
    values: I,
    capacity: usize,
) where
    I: Iterator<Item = u32> + Clone,
{
    // Baseline first, so an empty chart still reads as a chart rather than as a
    // rendering failure.
    let _ = Line::new(
        Point::new(at.x, at.y + height as i32),
        Point::new(at.x + width, at.y + height as i32),
    )
    .into_styled(PrimitiveStyle::with_stroke(INK, 1))
    .draw(frame);

    let peak = values.clone().max().unwrap_or(0);

    let mut caption = Text32::new();
    let _ = caption.push_str(label);
    if peak > 0 {
        let _ = caption.push_str("  peak ");
        let _ = write!(caption, "{}", peak);
    } else {
        let _ = caption.push_str("  none");
    }
    let _ = Text::with_baseline(
        &caption,
        Point::new(at.x, at.y + height as i32 + 3),
        MonoTextStyle::new(&FONT_6X10, INK),
        Baseline::Top,
    )
    .draw(frame);

    if peak == 0 || capacity == 0 {
        return;
    }

    // Column width comes from the ring's **capacity**, not from how much of it
    // is filled -- so bars keep their size as the chart fills and two readings
    // taken hours apart are the same shape.
    //
    // Drawing starts at the left edge and the iterator is the live tail
    // oldest-first, so a new device fills left to right and only begins
    // scrolling once the ring is genuinely full. Anchoring to the right instead
    // would show one bar at the far edge behind a day of blank columns, which
    // reads as "a day of silence, then this" -- a different and wrong story.
    let column = (width / capacity as i32).max(1);
    for (index, value) in values.enumerate() {
        if value == 0 {
            continue;
        }
        // At least one pixel for any non-zero bucket: a quiet hour that saw a
        // single distant strike must not render identically to one that saw
        // nothing, which is the difference between "calm" and "no data".
        let bar = ((value as u64 * height as u64 / peak as u64) as u32).max(1);
        let x = at.x + index as i32 * column;
        let _ = Rectangle::new(
            Point::new(x, at.y + height as i32 - bar as i32),
            Size::new(column.max(1) as u32, bar),
        )
        .into_styled(PrimitiveStyle::with_fill(INK))
        .draw(frame);
    }
}
